### ISSUE TITLE
NOT AN ISSUE: What's the best way to apply these patches via Cursed Legacy Fabric?

### ISSUE THREAD

**Issue by cocona20xx** [betacraftuk/legacyfix#1]
Heyo, I'm a contributor to the [Better than Wolves Community Edition project](https://github.com/BTW-Community), and legacyfix would be extremely useful to have patched ontop of our project.

What would be the best way of going about this, and as future-proofing for when launchers start having direct support for legacyfix, is there currently a way to check if legacyfix patches are already applied at startup and disable them from running again?

**Comment by Moresteck** [comment]
Hi. For now, you can see if a certain legacyfix patch is in place by checking the corresponding JVM argument.
As for Cursed Legacy, I'm not sure if that would work with LF. You'd probably be better off making a Fabric mod that includes LF's fixes.

I tried running the BTW mod with legacyfix on it (and with the M1 patch), but it appears unstable - I can join a world, but can't open any GUI, nor can i resize the game frame without it losing certain elements. BUT, same thing happens on vanilla 1.5.2, so it's to do with LF itself. I simply haven't tried release support yet, my main focus was pre-1.0.0 versions, and now it's 1.6-1.7 snapshots.
I'll make sure to properly support 1.5.2 when I'm done with sound handling.

Alternatively, you could make your mod run without applet, making it work on Silicon Macs. Plus, you'd also need to run [this](https://github.com/betacraftuk/legacyfix/blob/ecd2e9e6cb173ef8e4211dd697895649be0e1344/src/legacyfix/agent/LegacyFixAgent.java#L165) on tick to make it work. I see your mod has sound and skin handling figured out already, so making it use legacyfix could mess up some things.
