### ISSUE TITLE
Rendering rot on certain Intel graphics iGPUs

### ISSUE THREAD

**Issue by Moresteck** [betacraftuk/legacyfix#14]
## Cause: missing glClientActiveTexture calls in OpenGlHelper
Reference: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1294926-themastercavers-world?page=13#c294

**Comment by Moresteck** [comment]
Addressed by https://github.com/betacraftuk/legacyfix/commit/715dda9d24630aa389aace7fd872cd22191e0760, but needs testing

**Comment by Lassebq** [comment]
Fix confirmed?

**Comment by Moresteck** [comment]
> Fix confirmed?

Yes
